--NGAY 22 -4 - 2021
--TAO CSDL2 
--
CREATE   DATABASE  CSDL2 
GO
--SU DUNG CSDL2
USE CSDL2 
-- BANG NHAN VIEN 
CREATE TABLE NHANVIEN (
ID NVARCHAR (10) Primary key,
FullName NVARCHAR (50),
UserName NVARCHAR (15),
Pass NVARCHAR(20),
BirthDay DATE,
Email NVARCHAR(40),
SDT NVARCHAR (10),
GT NVARCHAR(1),
Avatar Nvarchar(50),
TrangThai bit 
)

-- BANG NHA SAN XUAT 
CREATE TABLE NSX
(
MANSX NVARCHAR (10)  PRIMARY KEY,
TEN NVARCHAR (50),
EMAIL NVARCHAR(40),
SDT NVARCHAR (10),
DCHI NVARCHAR (50),
TrangThai bit
)
select * from NSX

CREATE TABLE LOAI 
(
MALOAI INT ,
TENLOAI NVARCHAR(30),
CONSTRAINT PK_LOAI PRIMARY KEY (MALOAI),
trangthai bit
)
-- BANG SAN PHAM 
CREATE TABLE SANPHAM 
(
MASP NVARCHAR (10) ,
TENSP NVARCHAR (30),
MANSX NVARCHAR (10),
MALOAI INT ,
PRIMARY KEY(MASP),
CONSTRAINT FK_SANPHAM_NSX_MANSX FOREIGN KEY (MANSX) REFERENCES NSX(MANSX),
CONSTRAINT FK_SANPHAM_LOAI FOREIGN KEY (MALOAI) REFERENCES LOAI(MALOAI),
trangthai bit
)
--BANG SIZE SAN PHAM
CREATE TABLE SIZE(
MASIZE INT  ,
MOTA NVARCHAR(30)
CONSTRAINT PK_SIZE PRIMARY KEY (MASIZE),
trangthai bit

)
--BANG MAU SAN PHAM
CREATE TABLE MAU (
MAMAU NVARCHAR(30) ,
MOTA NVARCHAR(30)
CONSTRAINT PK_MAU PRIMARY KEY (MAMAU),
trangthai bit

)
--BANG LOAI SAN PHAM 

--BANG CHI TIET SAN PHAM 
CREATE TABLE CTSP(
MACTSP NVARCHAR(10) ,
MASP NVARCHAR (10) ,
MASIZE INT ,
MAMAU NVARCHAR(30) ,
DONGIA INT,
SLTON INT,
CONSTRAINT FK_CTSP_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
CONSTRAINT FK_CTSP_SIZE FOREIGN KEY (MASIZE) REFERENCES SIZE(MASIZE),
CONSTRAINT FK_CTSP_MAU FOREIGN KEY (MAMAU) REFERENCES MAU(MAMAU),
CONSTRAINT PK_CTSP PRIMARY KEY (MACTSP),
trangthai bit
)

-- BANG KHACH HANG 
CREATE table KHACHHANG (
MAKH NVARCHAR(10) PRIMARY KEY,
TENKH NVARCHAR(50),
SDT NVARCHAR(11),
DCHI NVARCHAR(50),
NGSINH DATE ,
EMAIL NVARCHAR(20),
GT nvarchar(3),
trangthai bit
)
-- BANG HOA DON
CREATE TABLE HOADON 
(
MAHD NVARCHAR (10) PRIMARY KEY,
MANV_LAP NVARCHAR (10) ,
NGLAP DATE,
THANHTIEN INT,
MAKH NVARCHAR(10) ,
DCHI NVARCHAR(50)
CONSTRAINT FK_HD_NhanVien_MANV_LAP FOREIGN KEY (MANV_LAP) REFERENCES NhanVien(ID),
CONSTRAINT FK_HD_KHACHHANG_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
trangthai bit
)
--BANG CHI TIET HOA DON 
CREATE TABLE CTHD(
MACTSP NVARCHAR (10),
MAHD NVARCHAR (10),
SL INT,
DONGIA INT,
CONSTRAINT FK_CTHD_HD_MAHD  FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
CONSTRAINT FK_CTHD_CTSP FOREIGN KEY (MACTSP) REFERENCES CTSP(MACTSP),
PRIMARY KEY (MAHD,MACTSP),
trangthai bit
)
--nhan vien ban dau 
insert into NHANVIEN(ID,FullName,UserName,Pass,BirthDay,Email,SDT,GT,Avatar,TrangThai)
values ('01', 'Dinh Van Tien', 'vtien','123','12/11/2001','0306191373@caothang.edu.vn','0327688127','1','tien.jpg',1)
--san pham ban dau 
